### ISSUE TITLE
in registration remove the 'org' field because it currently does nothing?

### ISSUE THREAD

**Issue by kcox40** [MissionSupport/MissionSupportDemo#80]

**Comment by rourke750** [comment]
Its just not used for us, we should prob add something where people select from a list of options

**Comment by mjung0802** [comment]
If we go from the "People select from a list of options" idea, then we could have a dropdown in Registration of the current orgs. The only issue comes from the ruleset, what do we do if a new user (no account yet, just registering) wants to sign up, but their org isn't listed? They can't create a new org, but they can't select one either.

I think it might be worth keeping org just because it's displayed in the admin dashboard for pending approvals, so people can self-identify there and help the admins know who they are, even if it's not used as an actual field/permission thing anywhere else in the app

**Comment by mjung0802** [comment]
Gonna assume we're keeping 'org' unless someone else wants to bring up a counterargument so closing
